version: '3.8'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      CLIENT_URL: ${CLIENT_URL}      
    ports:
      - "5432:5432"  

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database  
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}